# Generated by Django 2.2.7 on 2019-11-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorys',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
