# Generated by Django 2.2.7 on 2019-11-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20191110_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='gallery.Location'),
        ),
    ]
